### ISSUE TITLE
Feature: Terms & Conditions

### ISSUE THREAD

**Issue by StefanieKrohmann** [The-Agile-Avengers/icu-connect-frontend#221]

**Comment by Mariinja** [comment]
Terms and Conditions

Welcome to our awesome website! By using this website, you agree to the following terms and conditions that will make your browsing experience even more amazing. If you don't agree with these terms, it's like missing out on a virtual party, so please refrain from using our website.

Cookies, the Yummy Treats!

We love cookies! Not the kind you eat (though we love those too), but the digital cookies that make our website work smoothly. By using our website, you're giving us a virtual high-five to use these cookies. Don't worry, they don't have any calories, but they do help us enhance your browsing experience. For more details about how we use cookies, check out our Privacy Policy.

Sharing is Caring (Except for our Intellectual Property)

We're excited to share our awesome content with you, but please remember that all the cool stuff on this website belongs to us or our licensors. You can view and print pages for your personal enjoyment, but please don't get any wild ideas about republishing, selling, or copying our stuff. Sharing is caring, but not when it comes to our intellectual property!

Party Poopers (Linking Policy)

While we love making new friends, we may occasionally ask you to remove any links to our website that don't follow our rules. Please be a good party guest and respect our linking policy. We reserve the right to change these terms and conditions and our linking policy because we like to keep the party fresh and exciting.

You're Responsible for Your Content (Don't Be a Buzzkill)

We believe in freedom of expression, but please don't use our website to spread negativity or do anything illegal. You're responsible for the content you create or share, so keep it fun, respectful, and within the bounds of the law. If your content infringes on someone else's rights, you'll be responsible for the consequences. Let's keep the good vibes flowing!

No Gloomy Disclaimers (We're Here for Fun!)

We want you to have a blast on our website, so we've done our best to make it awesome. However, we can't guarantee that everything will be perfect or meet your expectations. So, we're not liable for any glitches, bloopers, or surprises you may encounter while partying with us. We're all about good times, but we're not responsible for anything beyond our control.
